# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170916_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Post'),
            preserve_default=False,
        ),
    ]
